#!/bin/bash

## Use CARTA desktop without Electron (primarily for RedHat6 remote servers)

DIRNAME=`dirname $0`

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

### There may be multiple users on the same server, so get unused ports
read LOWERPORT UPPERPORT < /proc/sys/net/ipv4/ip_local_port_range
while :
do
        FRONTEND_PORT="`shuf -i $LOWERPORT-$UPPERPORT -n 1`"
        WEBSOCKET_PORT="`shuf -i $LOWERPORT-$UPPERPORT -n 1`"
        ss -lpn | grep -q ":$FRONTEND_PORT" || break
        ss -lpn | grep -q ":$WEBSOCKET_PORT" || break
done

### Start the python http server (for python2 on RedHat servers)
cd $DIR
python -m SimpleHTTPServer $FRONTEND_PORT > /dev/null 2>&1 &

### Find the host IP address or server name
SERVER_NAME=$(hostname)

### Start the backend

## Check if log directory exists and if not, create it.
if [ ! -d $HOME/CARTA/log ]; then
        mkdir -p $HOME/CARTA/log
fi

logfilename=$HOME/CARTA/log/$(date +"%Y%m%d_%H%M%S_%Z").log

## Source the measures data
DIR="$( cd "$( pwd "${BASH_SOURCE[0]}" )" >/dev/null && pwd )/carta-backend/etc"

export CASAPATH="../../../../$DIR linux"

export LD_LIBRARY_PATH=$DIR/../lib:$LD_LIBRARY_PATH

## Get the number of threads on the system and double it for best performance
X=2
NPROCS=$(getconf _NPROCESSORS_CONF)
NTHREADS=$((NPROCS*X))

$DIR/../bin/carta_backend port=$WEBSOCKET_PORT folder=${1:-$HOME} threads=$NTHREADS >> $logfilename 2>&1 &

sleep 1

echo " "
echo "To access CARTA, please enter the following URL in your local web browser: "
echo " "
echo "$SERVER_NAME:$FRONTEND_PORT/?socketUrl=ws://$SERVER_NAME:$WEBSOCKET_PORT"
echo " "
echo " "

### Get the PIDs for the HTTP server and carta-backend
httpserver_pid=$(ps aux | grep $USER | grep '[p]ython -m SimpleHTTPServer' | awk '{print $2}')
carta_pid=$(ps aux | grep $USER | grep '[c]arta_backend' | awk '{print $2}')

### Wait for the user to enter 'q' before exiting
while true; do
    echo -en "Press q to close CARTA:"
    read input
    if [[ $input = "q" ]] || [[ $input = "Q" ]]
        then break
    else
       echo "" 
    fi
done

### Stop the HTTP server and carta_backend processes
kill $httpserver_pid
kill $carta_pid

### Go back to original directory
cd -
